import { Inter } from 'next/font/google'
import './globals.css'
import CarProvider from '@/context/CarProvider'

const inter = Inter({ subsets: ['latin'] })

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body suppressHydrationWarning={true} className={inter.className}>
        <CarProvider>
        {children}
        </CarProvider>
        </body>
    </html>
  )
}
